apiVersion: wg.krakensystems.co/v1alpha1
kind: Server
metadata:
  name: k8s-3
spec:
  publicKey: A0//xScnnJMGbXr5WRZ1VCpGM0c7vLRg/Dkvmcxywh0=
  address: "10.102.0.3"
  extraAllowedIPs:
  - "10.100.0.0/14"
  endpoint: 11.12.13.14:5555
