apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wg-operator
  namespace: wg-operator
rules:
- apiGroups:
  - wg.krakensystems.co
  resources:
  - '*'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
